APP:
  name: MyApp
  port: 3000
  host: localhost

jwt_secret: your_jwt_secret

cors:
  origin: "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowedHeaders:
    - Content-Type
    - Authorization

database:
  host : '123.57.39.28'
  port : 3306
  database : 'spinach_robot'
  user: 'root'
  password : 'Root332211#'

redis:
  host: localhost
  port: 6379
  password: your_redis_password
  db: 0


rateLimit:
  windowMs: 600000 # 15 分钟
  max: 1000 # 每个 IP 在 15 分钟内最多只能发出 100 个请求
  message: "Too many requests from this IP, please try again later."
  customHeader: "x-forwarded-for" # 自定义头部字段
