APP:
  name: MyApp
  walletPort: 3000
  gamePort: 3001
  payWalletPort: 3002
  host: localhost

jwt_secret: your_jwt_secret

botConfig:
  GameBotToken: '7840670913:AAHlRHjs_TJHpfXEHERi1leLkaz3uz9FHEQ'
  WalletToken: '7723665206:AAFEHMBvs8hW4CLgl9MvKSoISkENfaJ2NNk'

cors:
  origin: "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowedHeaders:
    - Content-Type
    - Authorization

database:
  host : 202.79.175.11
  port : 3306
  database : spinach_robot_test
  user: root
  password : 0287dfc565570ecd

redis:
  host: 202.79.175.11
  port: 6379
  password: rLJ45%ki@
  db: 1

rateLimit:
  windowMs: 600000 # 15 分钟
  max: 1000 # 每个 IP 在 15 分钟内最多只能发出 100 个请求
  message: "Too many requests from this IP, please try again later."
  customHeader: "x-forwarded-for" # 自定义头部字段
