app:
  name: MyApp
  walletPort: 3000
  gamePort: 3001
  payWalletPort: 3002
  host: localhost

jwt_secret: your_jwt_secret

botConfig:
  GameBotToken: '7840670913:AAGuk-XMILCw0nxFmnQbbuAXBxvzgrp274s'
  WalletToken: '7635600144:AAHELBLU6wF63MQ7j3o7A50DF7TleH6icls'
  WalletTokenTest: '7873009878:aah0mmdgevjyp5zvk9gbml_fbjveyh6ga-q'
  #WalletUrl: 'http://t.me/vertexpaybot'
  WalletUrl: 'http://t.me/sanjinzsbot'

cors:
  origin: "*"
  methods:
    - get
    - post
    - put
    - delete
  allowedHeaders:
    - Content-Type
    - Authorization

database:
  host : 127.0.0.1
  port : 3306
  database : spinach_robot_test
  user: root
  password : 0287dfc565570ecd

redis:
  host: 127.0.0.1
  port: 6379
  db: 1

rateLimit:
  windowMs: 600000 # 15 分钟
  max: 1000 # 每个 ip 在 15 分钟内最多只能发出 100 个请求
  message: "too many requests from this ip, please try again later."
  customHeader: "x-forwarded-for" # 自定义头部字段