app:
  name: myapp
  walletport: 3000
  gameport: 3001
  paywalletport: 3002
  host: localhost

jwt_secret: your_jwt_secret

botconfig:
  gamebottoken: '7840670913:aahlrhjs_tjhpfxeheri1lelkaz3uz9fheq'
  wallettoken: '7723665206:aafehmbvs8hw4clgl9mvksoiskenfaj2nnk'
  wallettokentest: '7873009878:aah0mmdgevjyp5zvk9gbml_fbjveyh6ga-q'
  walleturl: 'http://t.me/vertexpaybot'

cors:
  origin: "*"
  methods:
    - get
    - post
    - put
    - delete
  allowedheaders:
    - content-type
    - authorization

database:
  host : 127.0.0.1
  database : spinach_robot_test
  user: root
  password : 0287dfc565570ecd

redis:
  host: 127.0.0.1
  port: 6379
  password: rlj45%ki@
  db: 1

ratelimit:
  windowMs: 600000 # 15 分钟
  max: 1000 # 每个 ip 在 15 分钟内最多只能发出 100 个请求
  message: "too many requests from this ip, please try again later."
  customheader: "x-forwarded-for" # 自定义头部字段
